// Re-export all schemas from @repo/zod for use in the API
export {
  setupSchema,
  signinSchema,
  changePasswordSchema,
  createUserSchema,
  createLeadSchema,
  updateLeadSchema,
  createPipelineSchema,
  updatePipelineSchema,
  createPipelineStageSchema,
  updatePipelineStageSchema,
  createCampaignSchema,
  updateCampaignSchema,
  createPropertySchema,
  updatePropertySchema,
  createPropertyInterestSchema,
  updatePropertyInterestSchema,
  createInteractionSchema,
  createTaskSchema,
  updateTaskSchema,
  createMeetingSchema,
  updateMeetingSchema,
  createNoteSchema,
  updateNoteSchema,
  createDocumentSchema,
  type SetupInput,
  type SigninInput,
  type ChangePasswordInput,
  type CreateUserInput,
  type CreateLeadInput,
  type UpdateLeadInput,
  type CreatePipelineInput,
  type UpdatePipelineInput,
  type CreateCampaignInput,
  type UpdateCampaignInput,
  type CreatePropertyInput,
  type UpdatePropertyInput,
  type CreatePropertyInterestInput,
  type UpdatePropertyInterestInput,
  type CreateInteractionInput,
  type CreateTaskInput,
  type UpdateTaskInput,
  type CreateMeetingInput,
  type UpdateMeetingInput,
  type CreateNoteInput,
  type UpdateNoteInput,
  type CreateDocumentInput,
} from "@repo/zod";


